### ISSUE TITLE
I encountered the following 2 errors, where is the problem?

### ISSUE THREAD

**Issue by AnujMuth** [idfp/masquerade#1]
1. nimble install winim ptr_math
    Prompt: winim not found in any local packages.json, check internet for updated packages? [y/N]
    Answer: y
Downloading Official package list
    Success Package list downloaded.
       Tip: 6 messages have been suppressed, use --verbose to show them.
nimble.nim(683)          getDownloadInfo

    Error:  Package winim@any version not found.
------------------------------------------------------------------------------------------------------------------------------------
2.  masquerade.exe --payload="test.exe" --type="ReflectivePE" pict.jpg
[I] Embedded file: pict.jpg
Extension: jpg
[I] Using normal naming convention (double extension)
[W] Warning, this kind of name can be easily detected if your target set their explorer to show file extensions.
test.exe
[i] Using method: Reflective Run PE, write executable directly into memory.
[I] Compiling template file...
Hint: used config file 'C:\Users\Kelvin\.choosenim\toolchains\nim-2.0.0\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\Kelvin\.choosenim\toolchains\nim-2.0.0\config\config.nims' [Conf]
................................................................................................................................................................
C:\Users\Kelvin\Downloads\masquerade-main\masquerade-main\template\reflectivePE.nim(2, 8) Error: cannot open file: ptr_math

C:\Users\Kelvin\Downloads\masquerade-main\masquerade-main\template\reflectivePE.nim(2, 8) Error: cannot open file: ptr_math
fatal.nim(53)            sysFatal
Error: unhandled exception: index 1 not in 0 .. 0 [IndexDefect]

**Comment by idfp** [comment]
Hi, sorry for the late response. From the error you got, it is pretty clear that you couldn't install both Winim and ptr_math. This means the problem lies in the nimble itself instead of this program. Sadly I couldn't reproduce this issue on my machine so I couldn't really help either.

And it's already been a month, you probably already fixed it anyway.
